### ISSUE TITLE
Styling Rows / Columns

### ISSUE THREAD

**Issue by jordanjoecooper** [Stoiker/ember-light-table-hello-world#1]
Love the guide, 

At the moment I cannot see how in both the official docs or your example how we style the table , it looks great in the demo provided on the core repo, but  I do not see any CSS or SCSS for doing this ?

I might be being blind, but it would be great if you knew how to do this and could share.

**Comment by Stoiker** [comment]
Hi!

You mean like adding class attributes and stuff? 
Following https://guides.emberjs.com/v1.10.0/components/customizing-a-components-element/
one can add the following to a component, e.g. the class *Foo* to the table in kopemon-table.js

``` js
export default Component.extend({   
  classNames: ['Foo'],   
...   
});
```

and then add your style under app/styles/app.css, e.g.

``` css
.Foo{
  background-color: green;
}
```

Hope that helps.

*Edit*

After reading your headline again, I have to add the following:
To change the column headers one can do following the statement above:
``` js
export default Component.extend({   
  classNames: ['Foo'],   
    columns: computed(function() {
    return [ {
      label: 'Id',
      valuePath: 'id',
      width: '150px',
      classNames: ['Bar']
    },
...
});
```
and add your style in app.css .

In terms of rows that contain the actual data, one has (?) to implement a custom row component: https://github.com/offirgolan/ember-light-table/issues/507 or use the pre-defined css class *.lt-row*

**Comment by Stoiker** [comment]
@T4JC I hope this answers your question, if so I will close this issue

**Comment by jordanjoecooper** [comment]
@Stoiker  That answers it perfectly, thank you!
